// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_ScreenBaja.h"
#include "ui_ScreenStandard.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_gaugebajanotext_png);   // assets/GaugeBajaNoText.png
LV_IMG_DECLARE( ui_img_pointer_png);   // assets/Pointer.png
LV_IMG_DECLARE( ui_img_transmissiontempsymbolinverted_png);   // assets/TransmissionTempSymbolInverted.png
LV_IMG_DECLARE( ui_img_image_png);   // assets/image.png
LV_IMG_DECLARE( ui_img_rpm_symbol_inverted_png);   // assets/RPM_Symbol_Inverted.png
LV_IMG_DECLARE( ui_img_839238605);   // assets/ThrottlePosSymbol-Picsart-BackgroundRemover.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
