// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_ScreenStandard = NULL;lv_obj_t *ui_Speed2 = NULL;lv_obj_t *ui_ScaleStandard = NULL;lv_obj_t *ui_PointerStandard = NULL;lv_obj_t *ui_mph = NULL;lv_obj_t *ui_AcccelerationXYZ = NULL;lv_obj_t *ui_AcccelerationXYZData = NULL;lv_obj_t *ui_EngineCoolantTempSymbol = NULL;lv_obj_t *ui_EngineCoolantTempData = NULL;lv_obj_t *ui_RPMSymbol = NULL;lv_obj_t *ui_RPMData = NULL;lv_obj_t *ui_ThrottlePosSymbol = NULL;lv_obj_t *ui_ThrottlePosData = NULL;
// event funtions

// build funtions

void ui_ScreenStandard_screen_init(void)
{
ui_ScreenStandard = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenStandard, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Speed2 = lv_label_create(ui_ScreenStandard);
lv_obj_set_width( ui_Speed2, lv_pct(25));
lv_obj_set_height( ui_Speed2, lv_pct(18));
lv_obj_set_x( ui_Speed2, 40 );
lv_obj_set_y( ui_Speed2, 65 );
lv_obj_set_align( ui_Speed2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Speed2,"26");
lv_obj_set_style_text_color(ui_Speed2, lv_color_hex(0x42D0F5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Speed2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Speed2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Speed2, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_zoom(ui_Speed2, 256, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScaleStandard = lv_img_create(ui_ScreenStandard);
lv_img_set_src(ui_ScaleStandard, &ui_img_gaugebajanotext_png);
lv_obj_set_width( ui_ScaleStandard, LV_SIZE_CONTENT);  /// 240
lv_obj_set_height( ui_ScaleStandard, LV_SIZE_CONTENT);   /// 241
lv_obj_set_x( ui_ScaleStandard, 36 );
lv_obj_set_y( ui_ScaleStandard, 0 );
lv_obj_set_align( ui_ScaleStandard, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ScaleStandard, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ScaleStandard, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PointerStandard = lv_img_create(ui_ScreenStandard);
lv_img_set_src(ui_PointerStandard, &ui_img_pointer_png);
lv_obj_set_width( ui_PointerStandard, LV_SIZE_CONTENT);  /// 240
lv_obj_set_height( ui_PointerStandard, LV_SIZE_CONTENT);   /// 240
lv_obj_set_x( ui_PointerStandard, 36 );
lv_obj_set_y( ui_PointerStandard, 0 );
lv_obj_set_align( ui_PointerStandard, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PointerStandard, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_PointerStandard, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_PointerStandard, 200, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mph = lv_label_create(ui_ScreenStandard);
lv_obj_set_width( ui_mph, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mph, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mph, 36 );
lv_obj_set_y( ui_mph, 38 );
lv_obj_set_align( ui_mph, LV_ALIGN_CENTER );
lv_label_set_text(ui_mph,"mph");
lv_label_set_recolor(ui_mph,"true");

ui_AcccelerationXYZ = lv_label_create(ui_ScreenStandard);
lv_obj_set_width( ui_AcccelerationXYZ, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AcccelerationXYZ, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AcccelerationXYZ, -90 );
lv_obj_set_y( ui_AcccelerationXYZ, 108 );
lv_obj_set_align( ui_AcccelerationXYZ, LV_ALIGN_CENTER );
lv_label_set_text(ui_AcccelerationXYZ,"Accceleration XYZ:");

ui_AcccelerationXYZData = lv_label_create(ui_ScreenStandard);
lv_obj_set_width( ui_AcccelerationXYZData, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AcccelerationXYZData, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AcccelerationXYZData, 146 );
lv_obj_set_y( ui_AcccelerationXYZData, 108 );
lv_obj_set_align( ui_AcccelerationXYZData, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_AcccelerationXYZData,"0.00|0.00|0.00");

ui_EngineCoolantTempSymbol = lv_img_create(ui_ScreenStandard);
lv_img_set_src(ui_EngineCoolantTempSymbol, &ui_img_image_png);
lv_obj_set_width( ui_EngineCoolantTempSymbol, LV_SIZE_CONTENT);  /// 200
lv_obj_set_height( ui_EngineCoolantTempSymbol, LV_SIZE_CONTENT);   /// 200
lv_obj_set_x( ui_EngineCoolantTempSymbol, -141 );
lv_obj_set_y( ui_EngineCoolantTempSymbol, 57 );
lv_obj_set_align( ui_EngineCoolantTempSymbol, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_EngineCoolantTempSymbol, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_EngineCoolantTempSymbol, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_EngineCoolantTempSymbol,50);

ui_EngineCoolantTempData = lv_label_create(ui_ScreenStandard);
lv_obj_set_width( ui_EngineCoolantTempData, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_EngineCoolantTempData, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_EngineCoolantTempData, -138 );
lv_obj_set_y( ui_EngineCoolantTempData, 83 );
lv_obj_set_align( ui_EngineCoolantTempData, LV_ALIGN_CENTER );
lv_label_set_text(ui_EngineCoolantTempData,"0.00");

ui_RPMSymbol = lv_img_create(ui_ScreenStandard);
lv_img_set_src(ui_RPMSymbol, &ui_img_rpm_symbol_inverted_png);
lv_obj_set_width( ui_RPMSymbol, LV_SIZE_CONTENT);  /// 360
lv_obj_set_height( ui_RPMSymbol, LV_SIZE_CONTENT);   /// 360
lv_obj_set_x( ui_RPMSymbol, -138 );
lv_obj_set_y( ui_RPMSymbol, -97 );
lv_obj_set_align( ui_RPMSymbol, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RPMSymbol, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_RPMSymbol, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_RPMSymbol,35);

ui_RPMData = lv_label_create(ui_ScreenStandard);
lv_obj_set_width( ui_RPMData, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RPMData, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RPMData, -138 );
lv_obj_set_y( ui_RPMData, -65 );
lv_obj_set_align( ui_RPMData, LV_ALIGN_CENTER );
lv_label_set_text(ui_RPMData,"0.00");

ui_ThrottlePosSymbol = lv_img_create(ui_ScreenStandard);
lv_img_set_src(ui_ThrottlePosSymbol, &ui_img_839238605);
lv_obj_set_width( ui_ThrottlePosSymbol, LV_SIZE_CONTENT);  /// 600
lv_obj_set_height( ui_ThrottlePosSymbol, LV_SIZE_CONTENT);   /// 400
lv_obj_set_x( ui_ThrottlePosSymbol, -139 );
lv_obj_set_y( ui_ThrottlePosSymbol, -19 );
lv_obj_set_align( ui_ThrottlePosSymbol, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ThrottlePosSymbol, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ThrottlePosSymbol, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ThrottlePosSymbol,20);

ui_ThrottlePosData = lv_label_create(ui_ScreenStandard);
lv_obj_set_width( ui_ThrottlePosData, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ThrottlePosData, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ThrottlePosData, -140 );
lv_obj_set_y( ui_ThrottlePosData, 6 );
lv_obj_set_align( ui_ThrottlePosData, LV_ALIGN_CENTER );
lv_label_set_text(ui_ThrottlePosData,"0.00");

}

void ui_ScreenStandard_screen_destroy(void)
{
   if (ui_ScreenStandard) lv_obj_del(ui_ScreenStandard);

// NULL screen variables
ui_ScreenStandard= NULL;
ui_Speed2= NULL;
ui_ScaleStandard= NULL;
ui_PointerStandard= NULL;
ui_mph= NULL;
ui_AcccelerationXYZ= NULL;
ui_AcccelerationXYZData= NULL;
ui_EngineCoolantTempSymbol= NULL;
ui_EngineCoolantTempData= NULL;
ui_RPMSymbol= NULL;
ui_RPMData= NULL;
ui_ThrottlePosSymbol= NULL;
ui_ThrottlePosData= NULL;

}
