// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENSTANDARD_H
#define UI_SCREENSTANDARD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenStandard
extern void ui_ScreenStandard_screen_init(void);
extern void ui_ScreenStandard_screen_destroy(void);
extern lv_obj_t *ui_ScreenStandard;
extern lv_obj_t *ui_Speed2;
extern lv_obj_t *ui_ScaleStandard;
extern lv_obj_t *ui_PointerStandard;
extern lv_obj_t *ui_mph;
extern lv_obj_t *ui_AcccelerationXYZ;
extern lv_obj_t *ui_AcccelerationXYZData;
extern lv_obj_t *ui_EngineCoolantTempSymbol;
extern lv_obj_t *ui_EngineCoolantTempData;
extern lv_obj_t *ui_RPMSymbol;
extern lv_obj_t *ui_RPMData;
extern lv_obj_t *ui_ThrottlePosSymbol;
extern lv_obj_t *ui_ThrottlePosData;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

