// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENBAJA_H
#define UI_SCREENBAJA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenBaja
extern void ui_ScreenBaja_screen_init(void);
extern void ui_ScreenBaja_screen_destroy(void);
extern lv_obj_t *ui_ScreenBaja;
extern lv_obj_t *ui_SpeedGPS;
extern lv_obj_t *ui_ScaleBaja;
extern lv_obj_t *ui_PointerBaja;
extern lv_obj_t *ui_mphBaja;
extern lv_obj_t *ui_AcccelerationBajaXYZ;
extern lv_obj_t *ui_AcccelerationXYZBajaData;
extern lv_obj_t *ui_TempData;
extern lv_obj_t *ui_TempBar;
extern lv_obj_t *ui_TransmissionSymbol;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

