// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_ScreenBaja = NULL;lv_obj_t *ui_SpeedGPS = NULL;lv_obj_t *ui_ScaleBaja = NULL;lv_obj_t *ui_PointerBaja = NULL;lv_obj_t *ui_mphBaja = NULL;lv_obj_t *ui_AcccelerationBajaXYZ = NULL;lv_obj_t *ui_AcccelerationXYZBajaData = NULL;lv_obj_t *ui_TempData = NULL;lv_obj_t *ui_TempBar = NULL;lv_obj_t *ui_TransmissionSymbol = NULL;
// event funtions

// build funtions

void ui_ScreenBaja_screen_init(void)
{
ui_ScreenBaja = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenBaja, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SpeedGPS = lv_label_create(ui_ScreenBaja);
lv_obj_set_width( ui_SpeedGPS, lv_pct(25));
lv_obj_set_height( ui_SpeedGPS, lv_pct(18));
lv_obj_set_x( ui_SpeedGPS, 40 );
lv_obj_set_y( ui_SpeedGPS, 65 );
lv_obj_set_align( ui_SpeedGPS, LV_ALIGN_CENTER );
lv_label_set_text(ui_SpeedGPS,"26");
lv_obj_set_style_text_color(ui_SpeedGPS, lv_color_hex(0x42D0F5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SpeedGPS, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SpeedGPS, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SpeedGPS, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScaleBaja = lv_img_create(ui_ScreenBaja);
lv_img_set_src(ui_ScaleBaja, &ui_img_gaugebajanotext_png);
lv_obj_set_width( ui_ScaleBaja, LV_SIZE_CONTENT);  /// 240
lv_obj_set_height( ui_ScaleBaja, LV_SIZE_CONTENT);   /// 241
lv_obj_set_x( ui_ScaleBaja, 36 );
lv_obj_set_y( ui_ScaleBaja, 0 );
lv_obj_set_align( ui_ScaleBaja, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ScaleBaja, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ScaleBaja, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PointerBaja = lv_img_create(ui_ScreenBaja);
lv_img_set_src(ui_PointerBaja, &ui_img_pointer_png);
lv_obj_set_width( ui_PointerBaja, LV_SIZE_CONTENT);  /// 240
lv_obj_set_height( ui_PointerBaja, LV_SIZE_CONTENT);   /// 240
lv_obj_set_x( ui_PointerBaja, 36 );
lv_obj_set_y( ui_PointerBaja, 0 );
lv_obj_set_align( ui_PointerBaja, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PointerBaja, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_PointerBaja, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_PointerBaja, 200, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mphBaja = lv_label_create(ui_ScreenBaja);
lv_obj_set_width( ui_mphBaja, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mphBaja, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mphBaja, 36 );
lv_obj_set_y( ui_mphBaja, 38 );
lv_obj_set_align( ui_mphBaja, LV_ALIGN_CENTER );
lv_label_set_text(ui_mphBaja,"mph");
lv_label_set_recolor(ui_mphBaja,"true");

ui_AcccelerationBajaXYZ = lv_label_create(ui_ScreenBaja);
lv_obj_set_width( ui_AcccelerationBajaXYZ, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AcccelerationBajaXYZ, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AcccelerationBajaXYZ, -90 );
lv_obj_set_y( ui_AcccelerationBajaXYZ, 108 );
lv_obj_set_align( ui_AcccelerationBajaXYZ, LV_ALIGN_CENTER );
lv_label_set_text(ui_AcccelerationBajaXYZ,"Accceleration XYZ:");

ui_AcccelerationXYZBajaData = lv_label_create(ui_ScreenBaja);
lv_obj_set_width( ui_AcccelerationXYZBajaData, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AcccelerationXYZBajaData, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AcccelerationXYZBajaData, 146 );
lv_obj_set_y( ui_AcccelerationXYZBajaData, 108 );
lv_obj_set_align( ui_AcccelerationXYZBajaData, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_AcccelerationXYZBajaData,"0.00|0.00|0.00");

ui_TempData = lv_label_create(ui_ScreenBaja);
lv_obj_set_width( ui_TempData, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TempData, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TempData, -103 );
lv_obj_set_y( ui_TempData, 71 );
lv_obj_set_align( ui_TempData, LV_ALIGN_CENTER );
lv_label_set_text(ui_TempData,"0.00");

ui_TempBar = lv_bar_create(ui_ScreenBaja);
lv_bar_set_range(ui_TempBar, 0,1000);
lv_bar_set_value(ui_TempBar,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_TempBar, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_TempBar, 150);
lv_obj_set_height( ui_TempBar, 10);
lv_obj_set_x( ui_TempBar, -66 );
lv_obj_set_y( ui_TempBar, 49 );
lv_obj_set_align( ui_TempBar, LV_ALIGN_CENTER );
lv_obj_set_style_transform_angle(ui_TempBar, -900, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TransmissionSymbol = lv_img_create(ui_ScreenBaja);
lv_img_set_src(ui_TransmissionSymbol, &ui_img_transmissiontempsymbolinverted_png);
lv_obj_set_width( ui_TransmissionSymbol, LV_SIZE_CONTENT);  /// 200
lv_obj_set_height( ui_TransmissionSymbol, LV_SIZE_CONTENT);   /// 200
lv_obj_set_x( ui_TransmissionSymbol, -140 );
lv_obj_set_y( ui_TransmissionSymbol, 71 );
lv_obj_set_align( ui_TransmissionSymbol, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TransmissionSymbol, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_TransmissionSymbol, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_TransmissionSymbol,50);

}

void ui_ScreenBaja_screen_destroy(void)
{
   if (ui_ScreenBaja) lv_obj_del(ui_ScreenBaja);

// NULL screen variables
ui_ScreenBaja= NULL;
ui_SpeedGPS= NULL;
ui_ScaleBaja= NULL;
ui_PointerBaja= NULL;
ui_mphBaja= NULL;
ui_AcccelerationBajaXYZ= NULL;
ui_AcccelerationXYZBajaData= NULL;
ui_TempData= NULL;
ui_TempBar= NULL;
ui_TransmissionSymbol= NULL;

}
